In [2]:
import math

In [3]:
print (math.sqrt(16))

4.0

In [4]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

data={'Name':['John','Anna','Peter'], 'Age':[20,30,40]}
df=pd.DataFrame(data)
print(df)

    Name  Age
0   John   20
1   Anna   30
2  Peter   40

In [22]:
#error handling

try:
  print(10/0)
except Exception as e:
  print("Error: ",e)
finally:
  print("Continue")

Error:  division by zero
Continue